apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/salheb/k3s.git
    path: charts/argo-cd
    targetRevision: HEAD
  destination:
    server: https://api.julionogueira.net/argo
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true