apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 8gears.container-registry.com/library
    chart: n8n
    targetRevision: 0.25.2
    helm:
      values: |
        config:
          database:
            type: postgresdb
            postgresdb:
              host: 10.43.100.198
          generic:
            timezone: America/Sao_Paulo
          ssl_key:        # SSL Key for HTTPS Protocol - default: ''
          ssl_cert:       # SSL Cert for HTTPS Protocol - default: ''
        secret:
          database:
            postgresdb:
              user: n8n
              password: '2LW9amUv'
        # Set additional environment variables on the Deployment
        extraEnv:
          # Set this if running behind a reverse proxy and the external port is different from the port n8n runs on
          WEBHOOK_TUNNEL_URL: 'https://n8n.julionogueira.net/'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true