apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 8gears.container-registry.com/library/n8n
    chart: n8n
    targetRevision: 0.25.0
    helm:
      values: |
        config:
          database:
            type: postgresdb
            postgresdb:
              host: 10.43.148.216
        secret:
          database:
            postgresdb:
              password: 
                secretKeyRef:
                  name: n8ndbpass
                  key: pwd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true