apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    chart: bitnami/postgresql
    targetRevision: 16.0.5
    helm:
      values: |
        persistence:
          existingClaim: postgresql-storage-claim
        volumePermissions:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true