apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whatsapp-bridge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/salheb/k3s.git
    targetRevision: HEAD
    path: charts/whatsapp-bridge
  destination:
    server: https://kubernetes.default.svc
    namespace: whatsapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
