---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: whatsapp-bridge-secrets
  namespace: whatsapp
spec:
  encryptedData:
    mcp-bearer-token: AgCU3jrXarwblF3bzUfTS8MmTdJIRD34AB1RpVlqkWKQrtpAdM9mQbh4hepaLJqVDc15/42zxnJoeZto3GakVAlSJtQoNVmesH004RGg5ZGLti8gVzEQWPyu6hOF2tIkL4U4a/kymDdlWqnQdWn0/qz6PYhM4ok3gaITUG+2HHkjIpHVU2DmzyimJkT3Y8p4/2kqg17v3CXhJYeaGbq+EILA0OtvjsjhY7xfbu5i1/cpDBygedxFMSkR90Rga5ioHLoNjoOQb+EcS2GmJWphuvZzjOjQlsH8NbCGRLAMpfacc4hQpZ30tb2x+yojeY4rHTQR36i3R6eg+obPGv+Sv/3z6Kvjc1iXPoYvRpdG/ZlOB2GiKP3OyKnl69X74tije7MkCo607lyag3PFf2rU37ZPAVvf4shyFguE1ooN+JoArUPElk2LIWahdE4mO2THdou2R/miAIrMe176wG2kwB/C2vy0CVDgLYChObkxkvF3/nmiH7ti8JmuPp7s2OLb/JcNXceT9oGkf133jCCsHIzYMY1+LfFYGzhSzSADNBUcFesOEWtyMVKFDdi/8CVTpMUG9qbtk3vzAT3CrrUzadzrfVVdEsnyPtIOjzVyLN4uqFZsCBdWu0lEz4+nUkPAqBjupr5n8Q41ZEG6DbQIyQK6eSITEVIaf2TFlwnYmAAXvYPEToGzs9oEgx+bhwQd2cxsFw6jdg7wB71P8ZuQBo3WAH8udcFups8DMsI3OiA0E1Sy8YdLrMahR94+3w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: whatsapp-bridge-secrets
      namespace: whatsapp
